name: Trigger auto deployment for todo-apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/todo-apps-AutoDeployTrigger-440a2b5b-1258-4f20-ad9e-798cfbcae38c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TODOAPPS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: todocr.azurecr.io
          registryUsername: ${{ secrets.TODOAPPS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TODOAPPS_REGISTRY_PASSWORD }}
          containerAppName: todo-apps
          resourceGroup: ms-6th-project-01-05
          imageToBuild: todocr.azurecr.io/todo:${{ github.sha }}
          
            

     

